# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/ComputerScience/cs_COD_Spring_2022/Lab4/lab4/lab4.srcs/sources_1/ip/data_mem2/data_mem2.xci
# IP: The module: 'data_mem2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/ComputerScience/cs_COD_Spring_2022/Lab4/lab4/lab4.srcs/sources_1/ip/data_mem2/data_mem2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'data_mem2'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: D:/ComputerScience/cs_COD_Spring_2022/Lab4/lab4/lab4.srcs/sources_1/ip/data_mem2/data_mem2.xci
# IP: The module: 'data_mem2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/ComputerScience/cs_COD_Spring_2022/Lab4/lab4/lab4.srcs/sources_1/ip/data_mem2/data_mem2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'data_mem2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
