# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/Lab简介/Nexys4DDR_Master.xdc

# IP: ip/Data_Mem/Data_Mem.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Data_Mem || ORIG_REF_NAME==Data_Mem} -quiet] -quiet

# IP: ip/Instr_Mem/Instr_Mem.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Instr_Mem || ORIG_REF_NAME==Instr_Mem} -quiet] -quiet
