# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/ComputerScience/cs_COD_Spring_2022/Lab5/lab5/lab5.srcs/sources_1/ip/Instr_Mem_quick/Instr_Mem_quick.xci
# IP: The module: 'Instr_Mem_quick' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/ComputerScience/cs_COD_Spring_2022/Lab5/lab5/lab5.srcs/sources_1/ip/Instr_Mem_quick/Instr_Mem_quick_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Instr_Mem_quick'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: D:/ComputerScience/cs_COD_Spring_2022/Lab5/lab5/lab5.srcs/sources_1/ip/Instr_Mem_quick/Instr_Mem_quick.xci
# IP: The module: 'Instr_Mem_quick' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/ComputerScience/cs_COD_Spring_2022/Lab5/lab5/lab5.srcs/sources_1/ip/Instr_Mem_quick/Instr_Mem_quick_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Instr_Mem_quick'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
